baseURL = "http://scannell.me"
languageCode = "en-us"
theme = "ublogger"
title = "Simon Scannell's personal blog"

[params]
title = "Simon Scannell's personal blog"
author = "Simon Scannell"
description = "I am a self-taught Vulnerability Researcher"
profilePicture = "images/profile.jpg"
# customCss = ["css/tables.css"]
version = "2.0.X"

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Findings"
weight = 200
url = "/findings/"
identifier = "findings"

# Enable raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
