baseURL = "http://scannell.io"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "terminal"
title = "Simon Scannell's personal blog"
paginate = 5

[params]
title = "Simon Scannell's personal blog"
author = "Simon Scannell"
version = "2.0.X"

# required for terminal theme
fullWidthTheme = false
centerTheme = true
showLanguageSelector = false
themeColor = "pink"
contentTypeName = "posts"


[params.twitter]
creator = "scannell_simon"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Findings"
  weight = 200
  url = "/findings/"
  identifier = "findings"

  [[menu.main]]
  name = "About Me"
  weight = 300
  url = "/about/"
  identifier = "about"
